"""add owner details

Revision ID: 413cd6b0e195
Revises: 0cdb87599131
Create Date: 2023-10-24 20:17:38.208279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413cd6b0e195'
down_revision = '0cdb87599131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner')
    # ### end Alembic commands ###
