"""added

Revision ID: a17069d18c71
Revises: 050e757a3749
Create Date: 2023-12-23 23:33:08.295684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17069d18c71'
down_revision = '050e757a3749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppy', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
